name: Build and publish the container image

on: [ push ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build untagged
        uses: docker/build-push-action@v6
        if: github.ref_type != 'tag'
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Build and push tagged version
        uses: docker/build-push-action@v6
        if: github.ref_type == 'tag'
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Build and push latest
        uses: docker/build-push-action@v6
        if: github.ref_type == 'tag'
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
